# Tensor Introduction
Tensor is just a multidimentional array of numbers used to represent an input
it outputs a tensor 

# Goal of today
* Create tensors from different data sources like Python lists and NumPy arrays.

* Reshape and manipulate tensor dimensions to prepare data for model inputs.

* Use indexing and slicing techniques to access and filter specific parts of your data.

* Perform the mathematical and logical operations that form the basis of all neural network computations.


# imports


In [3]:
import torch
import numpy as np
import pandas as pd


# how do we create a "tensor"


In [ ]:
#using python list
x = torch.tensor([1,2,3],dtype= torch.float32)
print("Tensor data type",x.dtype)

Tensor data type torch.float32


In [9]:
#from numpy array
numpy_array = np.array([[1,2,3],[4,5,6]])
tensor = torch.from_numpy(numpy_array)
print("Tensor from numpy: \n\n",tensor)


Tensor from numpy: 

 tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
# All zeros , all ones and rand
zeros = torch.zeros(2,3)
print(f"Tensor with zeros \n{zeros}")
ones = torch.ones(2,3)
print(f"Tensor with ones \n {ones}")
rand = torch.rand(2,3)
print(f"Tensor with randoms \n {rand}")
range = torch.arange(0,10,step =1)
print(f"Arange {range}")


Tensor with zeros 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor with ones 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor with randoms 
 tensor([[0.2791, 0.1749, 0.5016],
        [0.2601, 0.6492, 0.9085]])
Arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
