# Tensor Introduction
Tensor is just a multidimentional array of numbers used to represent an input
it outputs a tensor 

# Goal

* Create tensors from different data sources like Python lists and NumPy arrays.

* Reshape and manipulate tensor dimensions to prepare data for model inputs.

* Use indexing and slicing techniques to access and filter specific parts of your data.

* Perform the mathematical and logical operations that form the basis of all neural network computations.


# imports


In [3]:
import torch
import numpy as np
import pandas as pd


# how do we create a "tensor"


In [6]:
#using python list
x = torch.tensor([1,2,3],dtype= torch.float32)
print("Tensor data type",x.dtype)

Tensor data type torch.float32


In [9]:
#from numpy array
numpy_array = np.array([[1,2,3],[4,5,6]])
tensor = torch.from_numpy(numpy_array)
print("Tensor from numpy: \n\n",tensor)


Tensor from numpy: 

 tensor([[1, 2, 3],
        [4, 5, 6]])


In [16]:
# All zeros , all ones and rand
zeros = torch.zeros(2,3)
print(f"Tensor with zeros \n{zeros}")
ones = torch.ones(2,3)
print(f"Tensor with ones \n {ones}")
rand = torch.rand(2,3)
print(f"Tensor with randoms \n {rand}")
range = torch.arange(0,10,step =1)
print(f"Arange {range}")


Tensor with zeros 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Tensor with ones 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Tensor with randoms 
 tensor([[0.2791, 0.1749, 0.5016],
        [0.2601, 0.6492, 0.9085]])
Arange tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# 2 Reshaping and manipulating
 the most commanon types of errors while in pytorch is shape errors.
 Your input has some dimentions and  your model expects some other dimentions u wil get "shape mismatch error"

 * your model usually expects batch of data so you need to always do [[]]

 


In [26]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(f" the shape is {x.shape}")

#unsquzze well if u want to add dimention at index 0 use this(very useful)
expaned = x.unsqueeze(0)
print(f"new dimentions {expaned.shape}")

#now if u want to remove dimentions use squueze
squeezed = expaned.squeeze()
print(f" After squuezing {squeezed.shape}")

#reshape a tensor 
new_shaped =  x.reshape(3,2)
print(f"after reshaping {new_shaped.shape} ")

#combining tensors
#(just make sure not to have dimension mismatch)
tensor_a = torch.tensor([[1,2,3],[4,5,6]])
tensor_b = torch.tensor([[7,8,9],[4,5,6]])
add = torch.cat((tensor_a,tensor_b),dim=1)
print(f"after concatination \n{add}")


 the shape is torch.Size([2, 3])
new dimentions torch.Size([1, 2, 3])
 After squuezing torch.Size([2, 3])
after reshaping torch.Size([3, 2]) 
after concatination 
tensor([[1, 2, 3, 7, 8, 9],
        [4, 5, 6, 4, 5, 6]])


# 3 Indexing and slicing 
 basically we use these techniques to grab specific parts of data and inspect them or selcting some subset of values for analysis
 this is similar to python indexing
 

In [33]:
x = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])


#now lets do some fun stuff 
print(f" this is accessing 0 th ro0w all elemnts {x[0]} ")
print(f"now i want lets say all the elemts of 0 th col {x[:,0]}")

# upto now we tried basically one elemnt each now  lets access range
# of elemnts also called subtensors
#[start:end:step](literally python!!!)
print(f"i want 1st and 2nd val of 1st two rows {x[:2,0:2]}")
print(f"step of 2 1st and 2 nd row {x[:2,::2]}")

#advaced indexing (boolean masking)
mask = x>5
masked_tensor = x[mask]
print(f"values after masking {masked_tensor}")


 this is accessing 0 th ro0w all elemnts tensor([1, 2, 3, 4]) 
now i want lets say all the elemts of 0 th col tensor([ 1,  5,  9, 13])
i want 1st and 2nd val of 1st two rows tensor([[1, 2],
        [5, 6]])
step of 2 1st and 2 nd row tensor([[1, 3],
        [5, 7]])
values after masking tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])


# mathematical and logical operations

this is main reason why we prefer pytorch beacause of its computational
efficieny and the ability to do parllel processing by using the gpu

and there is one more imp concept called "broad casting"
if u have one tensor of (1,3) shape and another of (1,0)
it makes it 1,3 as simple as it and its vice versa 


In [ ]:
a= torch.tensor([1,2,3])
b = torch.tensor([5,6,7])
dot_product = torch.matmul(a,b)
print(f"After doing dot product {dot_product}")

#broadcasting - automatic expansion of small tensors to match the shape of 
# large tensors is called broad casting

c = torch.tensor([1,2,3])
d= torch .tensor([[1],[2],[3]])
print(f"shape of c is {c.shape}")
print(f"shape of d is {d.shape}")
sum = c+d # we will get 3,3 shape 

print(f" the value is {sum},shape is {sum.shape} ")
#explanation see we first incvrease the dimention of c
# and then it applies broad casting so  its gonna be
#[[1,2,3],[1,2,3],[1,2,3]] something like this 
#now the d is gonna be [[1,1,1],[2,2,2],[3,3,3]]


#typecasting
tensor = torch.tensor([1,2,3,5])
float_tensor = tensor.float()
print(f" the tensor is {float_tensor} \n alos the dtype  is {float_tensor.dtype}")

After doing dot product 38
shape of c is torch.Size([3])
shape of d is torch.Size([3, 1])
 the value is tensor([[2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]]),shape is torch.Size([3, 3]) 
 the tensor is tensor([1., 2., 3., 5.]) 
 alos the dtype  is torch.float32
